#pragma once
#include <stdint.h>

#define PENGUIN_TRANSITION_UNHEALTHY_WIDTH 128
#define PENGUIN_TRANSITION_UNHEALTHY_HEIGHT 64
#define PENGUIN_TRANSITION_UNHEALTHY_FPS 5
#define PENGUIN_TRANSITION_UNHEALTHY_SECONDS 3
#define PENGUIN_TRANSITION_UNHEALTHY_FRAMES 15
#define PENGUIN_TRANSITION_UNHEALTHY_FRAME_SIZE 1024

extern const uint8_t penguin_transition_unhealthy_anim[PENGUIN_TRANSITION_UNHEALTHY_FRAMES][PENGUIN_TRANSITION_UNHEALTHY_FRAME_SIZE];
extern const int penguin_transition_unhealthy_offsets[PENGUIN_TRANSITION_UNHEALTHY_FRAMES];
