#pragma once
#include <stdint.h>

#define PENGUIN_IDLE_UNHEALTHY_WIDTH 128
#define PENGUIN_IDLE_UNHEALTHY_HEIGHT 64
#define PENGUIN_IDLE_UNHEALTHY_FPS 5
#define PENGUIN_IDLE_UNHEALTHY_SECONDS 3
#define PENGUIN_IDLE_UNHEALTHY_FRAMES 15
#define PENGUIN_IDLE_UNHEALTHY_FRAME_SIZE 1024

extern const uint8_t penguin_idle_unhealthy_anim[PENGUIN_IDLE_UNHEALTHY_FRAMES][PENGUIN_IDLE_UNHEALTHY_FRAME_SIZE];
extern const int penguin_idle_unhealthy_offsets[PENGUIN_IDLE_UNHEALTHY_FRAMES];
