"""
Script to extract GotchiLab_ animation byte arrays from C source files
and export them to web/animations.js for the Canvas OLED simulator.
"""

import os
import re
import json
import base64

ANIM_DIR = os.path.join(os.path.dirname(__file__), "..", "code", "src", "animations")
OUTPUT_JS = os.path.join(os.path.dirname(__file__), "..", "web", "js", "animations.js")

ANIMATION_MAP = {
    "IDLE": ("penguin_idle_anim.c", "penguin_idle_anim", "penguin_idle_offsets"),
    "FEED": ("penguin_feed_anim.c", "penguin_feed_anim", "penguin_feed_offsets"),
    "PET": ("penguin_pet_anim.c", "penguin_pet_anim", "penguin_pet_offsets"),
    "POP": ("penguin_pop_anim.c", "penguin_pop_anim", "penguin_pop_offsets"),
    "SLEEP": ("penguin_sleep_anim.c", "penguin_sleep_anim", "penguin_sleep_offsets"),
    "EGG": ("penguin_idle_egg_anim.c", "penguin_idle_egg_anim", "penguin_idle_egg_offsets"),
    "BIRTH": ("penguin_birth_anim.c", "penguin_birth_anim", "penguin_birth_offsets"),
    "UNHEALTHY": ("penguin_idle_unhealthy_anim.c", "penguin_idle_unhealthy_anim", "penguin_idle_unhealthy_offsets"),
}

def parse_anim_file(c_path, anim_var, offset_var):
    with open(c_path, "r", encoding="utf-8") as f:
        content = f.read()

    # Find offsets array
    offset_match = re.search(rf'{offset_var}\s*\[.*?\]\s*=\s*\{{([^}}]+)\}}', content)
    offsets = []
    if offset_match:
        offsets = [int(x.strip()) for x in offset_match.group(1).split(",") if x.strip()]

    # Find the main array content
    array_match = re.search(rf'{anim_var}\s*\[.*?\]\[.*?\]\s*=\s*\{{([\s\S]+?)\}};\s*(?:const|$)', content)
    if not array_match:
        raise ValueError(f"Could not find array {anim_var} in {c_path}")

    body = array_match.group(1)

    # Split into frame blocks enclosed by { ... }
    # Frame blocks: { ... 1024 bytes ... }
    frame_blocks = re.findall(r'\{([^{}]+)\}', body)

    frames = []
    for idx, block in enumerate(frame_blocks):
        # Find all hex numbers 0x..
        hex_values = re.findall(r'0x[0-9a-fA-F]{1,2}', block)
        if not hex_values:
            continue
        byte_vals = bytes(int(h, 16) for h in hex_values)
        if len(byte_vals) != 1024:
            print(f"Warning: {c_path} frame {idx} has {len(byte_vals)} bytes (expected 1024)")
        frames.append(byte_vals)

    return frames, offsets

def main():
    os.makedirs(os.path.dirname(OUTPUT_JS), exist_ok=True)
    animations_data = {}

    for key, (filename, anim_var, offset_var) in ANIMATION_MAP.items():
        c_path = os.path.join(ANIM_DIR, filename)
        if not os.path.exists(c_path):
            print(f"File not found: {c_path}")
            continue
        frames, offsets = parse_anim_file(c_path, anim_var, offset_var)
        print(f"Parsed {key}: {len(frames)} frames, {len(offsets)} offsets")

        # Encode frames as base64 strings for compact JS embedding
        frames_b64 = [base64.b64encode(f).decode('ascii') for f in frames]
        animations_data[key] = {
            "name": key,
            "width": 128,
            "height": 64,
            "fps": 5,
            "frameCount": len(frames),
            "offsets": offsets if offsets else [0] * len(frames),
            "framesB64": frames_b64
        }

    js_code = "// Autogenerated by scripts/extract_animations.py - DO NOT EDIT MANUALLY\n"
    js_code += "// Contains raw 128x64 monochromatic 1024-byte frames for GotchiLab_ Canvas OLED Simulator\n"
    js_code += "window.GOTCHI_ANIMATIONS = " + json.dumps(animations_data, indent=2) + ";\n"

    with open(OUTPUT_JS, "w", encoding="utf-8") as f:
        f.write(js_code)
    print(f"Successfully generated {OUTPUT_JS} ({os.path.getsize(OUTPUT_JS)} bytes)")

if __name__ == "__main__":
    main()
